language: node_js
node_js:
- '10'
cache:
  directories:
    - node_modules
before_script: 
- 
jobs:
  include:
    - script:
      - yarn compile
      - yarn test
    - script:
      - yarn compile
      - yarn coverage
      - cat ./coverage/lcov.info | coveralls