language: node_js

node_js:
- '12'

services:
  - docker

cache:
  directories:
    - node_modules

before_script: 
- cp .env.sample .env
- docker-compose up build

jobs:
  include:
    - script:
      - docker-compose up test
    - script:
      - docker-compose up coverage